// resources/js/components/MyComponent.vue
<template>
    <div class="container">
        <p>{{msg}}</p>
        <hr />
        <ul>
            <li v-for="(person) in people" :key="person.id">
                {{person.id}}: {{person.name}} [{{person.mail}}] ({{person.age}})
            </li>
        </ul>
    </div>
</template>

<script>
    export default {
        mounted(){
            axios.get('/hello/json').then(response => {
                this.people = response.data;
                this.msg = 'get data!';
            });
        },
        data:function(){
            return {
                msg: 'wait...',
                name: '',
                people: []
            };
        }
    }
</script>

// resources/ngapp/src/app/my/my.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl } from '@angular/forms';
import axios from 'axios';

@Component({
  selector: 'app-my',
  templateUrl: './my.component.html',
  styleUrls: ['./my.component.css']
})
export class MyComponent implements OnInit {

  message:string;
  input:FormControl;

  constructor() { }

  ngOnInit(): void {
    this.message = 'please input your name:';
    this.input = new FormControl('noname');
  }

  doAction() {
    axios.get(`/hello/json/${this.input.value}`).then(response => {
      const person = response.data;
      const msg = `${person.id}:${person.name} [${person.mail}] (${person.age})`;
      this.message = msg;
  });
  }
}

<div>
  <p>{{message}}</p>
  <input type="text" [formControl]="input" />
  <button (click)="doAction()">Click</button>
</div>
